# Generated by Django 3.1.5 on 2021-02-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20210216_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='customer_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
