# Generated by Django 3.1.5 on 2021-02-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_invoices_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='past_due_61_90',
            field=models.IntegerField(default=0),
        ),
    ]
